version: "3.1"
services:
  postgres:
    image: postgres:14.2-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: banking
    ports:
      - "5432:5432"
    deploy:
      resources:
        limits:
          memory: '512M'
          cpus: '1'